config/routes.rb
Pictr::Application.routes.draw do
  devise_for :users
  resources :albums
  resources :photos
  resources :users
  root :to => "static_pages#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    if user.persisted?
      can :manage, Album do |album|
        album.user_id == user.id
      end
      can :manage, Photo do |photo|
        photo.album.user == user
      end
      can :create, Photo do |photo|
        photo.album.user == user
      end
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base

  validates :name, :presence => true

  has_many :photos, :inverse_of => :album, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :photos, allow_destroy: true

end

app/models/photo.rb
class Photo < ActiveRecord::Base


  validates :name, :presence => true
  validates :album, :presence => true

  belongs_to :album

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :trackable, 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :albums
  has_many :photos, :through => :albums  

  validates :username, :uniqueness => true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.new(album_params)
    if @album.save
      flash[:notice] = "Your album has been created."
      redirect_to current_user
    else 
      flash[:alert] = "Something went wrong."
      render :new
    end
    authorize! :manage, @album
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(params[:album].permit(:name))
      flash[:notice] = "Album name updated."
      redirect_to @album
    else
      render :edit
    end
  end
  
  def destroy
    @album = Album.find(params[:id])
    @name = @album.name
    @album.destroy
    flash[:notice] = "Your album #{@name} has been destroyed."
    redirect_to root_path
    authorize! :manage, @album
  end

private
  def album_params
    params.require(:album).permit(:name, :photos_attributes => [:album_id, :name, :image])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    if params[:search]
      @query = params[:search]
      @results = Photo.basic_search(@query)
      render :search_results
    else
      @photos = Photo.all
      render :index
    end

  end

  def new
    respond_to do |format|
      format.html { @photo = Photo.new(photo_params) }
      format.js { @photo = Photo.new(photo_params) }
    end  
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Your photo has been added."
      redirect_to @photo.album
    else
      flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    authorize! :manage, @photo
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(params[:photo].permit(:image, :name, :album_id))
      flash[:notice] = "Photo updated."
      redirect_to @photo.album
    else
      render :edit
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    authorize! :manage, @photo
    @name = @photo.name
    @album = @photo.album
    @photo.destroy
    flash[:notice] = "Your photo #{@name} has been destroyed." 
    redirect_to @album
  end

private
  def photo_params
    params.require(:photo).permit(:name, :image, :album_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to current_user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div class="album">
  <%= link_to (image_tag album.photos.first.image.url(:medium)), album if album.photos.first %>
  <div class="album-listing">
    <%= link_to album.name, album %>
  </div>
</div>

app/views/albums/edit.html.erb
 <h1>Edit <%= @album.name %></h1>

 <%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Update", :class => "btn btn-primary" %>
<% end %>

app/views/albums/index.html.erb
<h1>Everyone's Albums</h1>

<ul>
  <% @albums.each do |album| %>
    <li><%= render album %>by <%= album.user.username %></li>
  <% end %>
</ul>    

app/views/albums/new.html.erb
<h1>Make a new album</h1>
<% if @album.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @album.errors.full_messages.each do |message| %>
      <li class="alert alert-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_for @album, :html => {:multipart => true} do |main_form| %>
    <%= main_form.label :name, 'Album Name' %>
    <%= main_form.text_field :name %>
    <div>
      <%= main_form.fields_for :photos, @album.photos.new do |f| %>
        <%= f.hidden_field :album_id %>
        <div class="new_form">
          <%= f.label :name, 'Image Name' %>
          <%= f.text_field :name %>
          <div class="new_form">
            <%= f.label :image, 'Upload File' %>
            <%= f.file_field :image %>
          </div>
        </div>
      <% end %>
    </div>  
  <%= main_form.submit "submit", :class => "btn btn-primary" %>
<% end %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<% if can? :manage, @album %>
  <div class="btn-group">
    <%= link_to "Edit Album", edit_album_path, :class => "btn btn-default" %>
    <%= link_to "Delete Album", album_path, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-default"%>
    <%= link_to "Add a photo", new_photo_path(:photo => {album_id: @album.id}), :class => "btn btn-default", id: "new_link", remote: true %>
  </div>
<% end %>
<% @album.photos.each do |photo| %>
  <%= render photo %>
<% end %>  

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <ul class='nav navbar-nav pull-left'>
    <li><%= link_to "Pictr", root_path, :class => "navbar-brand" %></li>
    <li><%= link_to "All Albums", albums_path %></li>
    <li><%= link_to "All Photos", photos_path %></li>
  </ul>  

  <ul class='nav navbar-nav pull-right'>
    <% if user_signed_in? %>
      <li class="navbar-text">Signed in as <%= current_user.username %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
    <%= form_tag photos_path, :method => 'get' do %>
      <%= label_tag :search, 'Search photos' %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :class => 'btn btn-primary' %>
    <% end %>

   </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

<%= yield %>

</div>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for :photo, :url => "/photos/#{@photo.id}", :method => 'patch' do |f| %>
  <%= f.hidden_field :album_id %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit "Update", :class => 'btn btn-type-primary' %>
<% end %>  

app/views/photos/_photo.html.erb
<div class="photo">
  <%= link_to (image_tag photo.image.url(:medium)), photo %>
  <div>
    <%= link_to photo.name, photo %>
    <%= photo.created_at.strftime("Uploaded on %B %e, %Y") %>
  </div>
  <% if can? :manage, photo %>
    <div class="btn-group">
      <%= link_to "Edit photo", edit_photo_path(:id => photo.id), :class => "btn btn-default" %>
      <%= link_to "Delete photo", photo_path(:id => photo.id), :method => :delete,  :data => { :confirm => 'Are you sure you want to delete this?' }, :class => "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/photos/_upload.html.erb
<%= form_for @photo do |f| %>
  <%= f.hidden_field :album_id %>
  <%= f.label :name, 'Image Name' %>
  <%= f.text_field :name %>
  <div class="new_form">
    <%= f.label :image, 'Upload File' %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit "Upload", :class => "btn btn-primary" %>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit your photo</h1>
<%= render 'form' %>

app/views/photos/index.html.erb
<h1> Everyone's Photos </h1>

<ul>
  <% @photos.each do |photo| %>
    <li><%= render photo %>by <%= photo.album.user.username %></li>
  <% end %>
</ul>

app/views/photos/new.html.erb
<h1>Add a photo</h1>
<% if @photo.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @photo.errors.full_messages.each do |message| %>
      <li class="alert alert-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/photos/new.js.erb
$('#new_link').hide().after('<%= j render("upload") %>');

app/views/photos/search_results.html.erb
<h1>Search Results</h1>
<% "Photos containing '#{@query}'" %>



<% if @results.any? %>
  <ul>
    <% @results.each do |photo| %>
      <li><%= render photo %></li>
      <li>by <%= photo.album.user.username %></li>
    <% end %>
  </ul>
<% else %>
  <p>No photos found.</p>
<% end %>

<% link_to root_path %>

app/views/photos/show.html.erb
<h1><%= @photo.name %></h1>
<h3>In the album <%= link_to @photo.album.name, @photo.album %></h3>
<%= render @photo %>

app/views/static_pages/index.html.erb
<div class='jumbotron'>

  <h1>Pictr</h1>

  <p>Give us your photos!</p>

  <%= link_to "Sign in", new_user_session_path, :class => 'btn btn-primary' %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary' %>

</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>Here are your photo albums:</h3>
<div class="btn-group">
<%= link_to "Create an album", new_album_path, :class => "btn btn-primary" %>
</div>

<% @user.albums.each do |album| %>
  <%= render album %>
<% end %>